import { Building2, Edit3, Eye, ShieldCheck, Trash2, UserCheck, Users } from 'lucide-react'
import { useEffect, useState } from 'react'
import { Link } from 'react-router-dom'
import { PropertyForm, propertyFormData } from '../../components/dashboard/PropertyForm'
import { api, type AdminOverview, type AdminUser, type AgentApplication, type ManagedProperty } from '../../services/api'
import type { User } from '../../types'
import { StatCards } from '../../components/dashboard/StatCards'

export function AdminOverviewPage(){const [data,setData]=useState<AdminOverview>();useEffect(()=>{api.adminOverview().then(setData)},[]);if(!data)return <div className="dashboard-empty">Loading platform overview…</div>;return <><div className="dashboard-title"><div><p>ADMINISTRATION</p><h1>Platform overview</h1></div></div><StatCards items={[[Users,data.totalUsers,'Registered users'],[UserCheck,data.totalAgents,'Approved agents'],[Building2,data.totalListings,'Total listings'],[ShieldCheck,data.pendingApplications,'Pending applications']]}/><section className="dashboard-panel"><div className="panel-heading"><h2>Recent properties</h2><Link to="/admin/properties">View all properties</Link></div><div className="recent-properties">{data.recentProperties.map(item=><article key={item.id}><img src={item.imageUrl}/><span><strong>{item.title}</strong><small>{item.address}, {item.city}</small><small>{item.agent.fullName} · {new Date(item.createdAt).toLocaleDateString()}</small></span><b>€{item.price.toLocaleString()}</b><Link to={`/properties/${item.slug}`}>View</Link></article>)}</div></section></>}

export function AdminUsersPage(){const [items,setItems]=useState<AdminUser[]>([]);const load=()=>api.adminUsers().then(r=>setItems(r.items));useEffect(()=>{load()},[]);async function toggle(user:AdminUser){await api.updateUser(user.id,{isActive:!user.isActive});load()}async function role(user:AdminUser,value:'user'|'agent'){await api.updateUser(user.id,{role:value});load()}return <><div className="dashboard-title"><div><p>ACCOUNTS</p><h1>Users</h1></div></div><section className="dashboard-panel table-panel users-table"><table><thead><tr><th>User</th><th>Role</th><th>Joined</th><th>Status</th><th/></tr></thead><tbody>{items.map(user=><tr key={user.id}><td><strong>{user.fullName}</strong><small className="block">{user.email}</small></td><td>{user.role==='admin'?<span className="status">Admin</span>:<select className="role-select" value={user.role} onChange={e=>role(user,e.target.value as 'user'|'agent')}><option value="user">Normal User</option><option value="agent">Agent</option></select>}</td><td>{new Date(user.createdAt).toLocaleDateString()}</td><td>{user.isActive?'Active':'Disabled'}</td><td><button className="table-action" onClick={()=>toggle(user)}>{user.isActive?'Disable':'Enable'}</button></td></tr>)}</tbody></table></section></>}

export function AdminPropertiesPage(){const [items,setItems]=useState<(ManagedProperty&{agent:User})[]>([]);const [agents,setAgents]=useState<User[]>([]);const [editing,setEditing]=useState<(ManagedProperty&{agent:User})>();const [feedback,setFeedback]=useState('');const load=()=>Promise.all([api.adminProperties(),api.adminUsers()]).then(([properties,users])=>{setItems(properties.items);setAgents(users.items.filter(user=>user.role==='agent'&&user.isActive))});useEffect(()=>{load()},[]);async function remove(id:number){if(!confirm('Delete this listing from the marketplace?'))return;await api.deleteProperty(id);load()}async function save(form:FormData){if(!editing)return;try{await api.updateProperty(editing.id,propertyFormData(form));setEditing(undefined);setFeedback('Property updated successfully.');load()}catch(error){setFeedback(error instanceof Error?error.message:'Unable to update property.')}}return <><div className="dashboard-title"><div><p>MODERATION</p><h1>All properties</h1></div></div>{feedback&&<div className="form-feedback">{feedback}</div>}<section className="dashboard-panel table-panel"><table><thead><tr><th>Property</th><th>Agent</th><th>Price</th><th>Status</th><th>Actions</th></tr></thead><tbody>{items.map(item=><tr key={item.id}><td><div className="table-property"><img src={item.imageUrl}/><span><strong>{item.title}</strong><small>{item.city}</small></span></div></td><td>{item.agent.fullName}</td><td>€{item.price.toLocaleString()}</td><td><span className={`status ${item.status}`}>{item.status}</span></td><td><div className="property-actions"><Link title="View property" to={`/properties/${item.slug}`}><Eye/></Link><button title="Edit property" onClick={()=>setEditing(item)}><Edit3/></button><button title="Delete property" onClick={()=>remove(item.id)}><Trash2/></button></div></td></tr>)}</tbody></table></section>{editing&&<PropertyForm item={editing} agents={agents} onClose={()=>setEditing(undefined)} onSave={save}/>}</>}

export function AdminApplicationsPage(){const [items,setItems]=useState<AgentApplication[]>([]);const load=()=>api.adminApplications().then(r=>setItems(r.items));useEffect(()=>{load()},[]);async function viewCv(id:number){const blob=await api.cv(id);window.open(URL.createObjectURL(blob),'_blank','noopener,noreferrer')}async function review(id:number,status:'approved'|'rejected'){await api.reviewApplication(id,status);load()}return <><div className="dashboard-title"><div><p>TRUST & QUALITY</p><h1>Agent applications</h1></div></div><section className="application-list">{items.map(item=><article key={item.id}><div className="application-head"><div className="avatar">{item.fullName.split(' ').map(part=>part[0]).join('').slice(0,2)}</div><div><h3>{item.fullName}</h3><p>{item.email} · {item.phone}</p></div><span className={`status ${item.status}`}>{item.status}</span></div><dl><div><dt>Location</dt><dd>{item.city}</dd></div><div><dt>Agency</dt><dd>{item.agencyName||'Independent'}</dd></div><div><dt>Experience</dt><dd>{item.experience||'Not specified'}</dd></div></dl><blockquote>{item.message}</blockquote>{item.cvUrl&&<button className="cv-link" onClick={()=>viewCv(item.id)}>View CV · {item.cvName}</button>}{item.status==='pending'&&<div className="review-actions"><button onClick={()=>review(item.id,'rejected')}>Reject</button><button className="primary-button" onClick={()=>review(item.id,'approved')}>Approve agent</button></div>}</article>)}{!items.length&&<div className="dashboard-empty">No applications to review.</div>}</section></>}
