import { Building2, Edit3, Eye, ShieldCheck, Trash2, UserCheck, Users, X } from 'lucide-react'
import { useEffect, useState } from 'react'
import { Link } from 'react-router-dom'
import { api, type AdminOverview, type AdminUser, type AgentApplication, type ManagedProperty } from '../../services/api'
import type { User } from '../../types'
import { StatCards } from '../../components/dashboard/StatCards'

export function AdminOverviewPage(){const [data,setData]=useState<AdminOverview>();useEffect(()=>{api.adminOverview().then(setData)},[]);if(!data)return <div className="dashboard-empty">Loading platform overview…</div>;return <><div className="dashboard-title"><div><p>ADMINISTRATION</p><h1>Platform overview</h1></div></div><StatCards items={[[Users,data.totalUsers,'Registered users'],[UserCheck,data.totalAgents,'Approved agents'],[Building2,data.totalListings,'Total listings'],[ShieldCheck,data.pendingApplications,'Pending applications']]}/><section className="dashboard-panel admin-note"><h2>Marketplace operations</h2><p>Review the platform’s listings, accounts and agent applications from the navigation. Destructive actions remain deliberately limited.</p></section></>}

export function AdminUsersPage(){const [items,setItems]=useState<AdminUser[]>([]);const load=()=>api.adminUsers().then(r=>setItems(r.items));useEffect(()=>{load()},[]);async function toggle(user:AdminUser){await api.updateUser(user.id,!user.isActive);load()}return <><div className="dashboard-title"><div><p>ACCOUNTS</p><h1>Users</h1></div></div><section className="dashboard-panel table-panel"><table><thead><tr><th>User</th><th>Role</th><th>Joined</th><th>Status</th><th/></tr></thead><tbody>{items.map(user=><tr key={user.id}><td><strong>{user.fullName}</strong><small className="block">{user.email}</small></td><td><span className="status">{user.role}</span></td><td>{new Date(user.createdAt).toLocaleDateString()}</td><td>{user.isActive?'Active':'Disabled'}</td><td><button className="table-action" onClick={()=>toggle(user)}>{user.isActive?'Disable':'Enable'}</button></td></tr>)}</tbody></table></section></>}

export function AdminPropertiesPage(){const [items,setItems]=useState<(ManagedProperty&{agent:User})[]>([]);const [editing,setEditing]=useState<(ManagedProperty&{agent:User})>();const load=()=>api.adminProperties().then(r=>setItems(r.items));useEffect(()=>{load()},[]);async function remove(id:number){if(!confirm('Delete this listing from the marketplace?'))return;await api.deleteProperty(id);load()}async function save(form:FormData){if(!editing)return;await api.updateProperty(editing.id,Object.fromEntries(form) as Record<string,unknown>);setEditing(undefined);load()}return <><div className="dashboard-title"><div><p>MODERATION</p><h1>All properties</h1></div></div><section className="dashboard-panel table-panel"><table><thead><tr><th>Property</th><th>Agent</th><th>Price</th><th>Status</th><th>Actions</th></tr></thead><tbody>{items.map(item=><tr key={item.id}><td><div className="table-property"><img src={item.imageUrl}/><span><strong>{item.title}</strong><small>{item.city}</small></span></div></td><td>{item.agent.fullName}</td><td>€{item.price.toLocaleString()}</td><td><span className={`status ${item.status}`}>{item.status}</span></td><td><Link title="View property" to={`/properties/${item.slug}`}><Eye/></Link><button title="Edit property" onClick={()=>setEditing(item)}><Edit3/></button><button title="Delete property" onClick={()=>remove(item.id)}><Trash2/></button></td></tr>)}</tbody></table></section>{editing&&<div className="modal-backdrop"><section className="property-form"><button className="modal-close" onClick={()=>setEditing(undefined)}><X/></button><p>ADMIN MODERATION</p><h2>Edit property</h2><form action={save}><input name="title" defaultValue={editing.title} required/><textarea name="description" defaultValue={editing.description} required/><div className="form-row"><input name="price" type="number" defaultValue={editing.price} required/><input name="areaSqm" type="number" defaultValue={editing.areaSqm} required/></div><div className="form-row"><select name="purpose" defaultValue={editing.purpose}><option value="sale">For sale</option><option value="rent">For rent</option></select><select name="propertyType" defaultValue={editing.propertyType}><option value="apartment">Apartment</option><option value="house">House</option><option value="villa">Villa</option><option value="commercial">Commercial</option><option value="land">Land</option></select></div><div className="form-row"><input name="city" defaultValue={editing.city} required/><input name="address" defaultValue={editing.address} required/></div><div className="form-row"><input name="bedrooms" type="number" defaultValue={editing.bedrooms}/><input name="bathrooms" type="number" defaultValue={editing.bathrooms}/></div><button className="primary-button">Save moderation changes</button></form></section></div>}</>}

export function AdminApplicationsPage(){const [items,setItems]=useState<AgentApplication[]>([]);const load=()=>api.adminApplications().then(r=>setItems(r.items));useEffect(()=>{load()},[]);async function review(id:number,status:'approved'|'rejected'){await api.reviewApplication(id,status);load()}return <><div className="dashboard-title"><div><p>TRUST & QUALITY</p><h1>Agent applications</h1></div></div><section className="application-list">{items.map(item=><article key={item.id}><div className="application-head"><div className="avatar">{item.fullName.split(' ').map(part=>part[0]).join('').slice(0,2)}</div><div><h3>{item.fullName}</h3><p>{item.email} · {item.phone}</p></div><span className={`status ${item.status}`}>{item.status}</span></div><dl><div><dt>Location</dt><dd>{item.city}</dd></div><div><dt>Agency</dt><dd>{item.agencyName||'Independent'}</dd></div><div><dt>Experience</dt><dd>{item.experience||'Not specified'}</dd></div></dl><blockquote>{item.message}</blockquote>{item.status==='pending'&&<div className="review-actions"><button onClick={()=>review(item.id,'rejected')}>Reject</button><button className="primary-button" onClick={()=>review(item.id,'approved')}>Approve agent</button></div>}</article>)}{!items.length&&<div className="dashboard-empty">No applications to review.</div>}</section></>}
