import { Heart, KeyRound, Settings, UserRound } from 'lucide-react'
import { useEffect, useState } from 'react'
import { useSearchParams } from 'react-router-dom'
import { PropertyCard } from '../components/property/PropertyCard'
import { useAuth } from '../context/AuthContext'
import { api } from '../services/api'
import type { Property } from '../types'

export function ProfilePage(){
  const auth=useAuth();const [params,setParams]=useSearchParams();const tab=(params.get('tab')||'profile') as 'profile'|'saved'|'settings';const [saved,setSaved]=useState<Property[]>([]);const [feedback,setFeedback]=useState('')
  useEffect(()=>{if(tab==='saved')api.favorites().then(r=>setSaved(r.items))},[tab])
  if(!auth.user)return <div className="empty page-state">Please sign in to view your profile.</div>
  async function update(form:FormData){try{await api.updateProfile(Object.fromEntries(form) as Record<string,string>);setFeedback('Profile updated successfully.')}catch(error){setFeedback(error instanceof Error?error.message:'Unable to update profile.')}}
  async function password(form:FormData){const next=String(form.get('newPassword'));if(next!==form.get('confirmPassword')){setFeedback('New passwords do not match.');return}try{const r=await api.changePassword(String(form.get('currentPassword')),next);setFeedback(r.message)}catch(error){setFeedback(error instanceof Error?error.message:'Unable to change password.')}}
  return <div className="profile-page"><aside><div className="profile-avatar">{auth.user.firstName[0]}{auth.user.lastName[0]}</div><h2>{auth.user.fullName}</h2><p>{auth.user.email}</p><button className={tab==='profile'?'active':''} onClick={()=>setParams({tab:'profile'})}><UserRound/> Profile</button><button className={tab==='saved'?'active':''} onClick={()=>setParams({tab:'saved'})}><Heart/> Saved homes</button><button className={tab==='settings'?'active':''} onClick={()=>setParams({tab:'settings'})}><KeyRound/> Change password</button></aside><main>{tab==='profile'?<><p className="eyebrow green">ACCOUNT</p><h1>Profile details</h1><form action={update} className="profile-form"><div className="form-row"><label>First name<input name="firstName" defaultValue={auth.user.firstName}/></label><label>Last name<input name="lastName" defaultValue={auth.user.lastName}/></label></div><label>Email<input value={auth.user.email} disabled/></label><label>Phone number<input name="phone" defaultValue={auth.user.phone}/></label><button className="primary-button"><Settings/> Save changes</button></form></>:tab==='saved'?<><p className="eyebrow green">YOUR COLLECTION</p><h1>Saved homes</h1>{saved.length?<div className="property-grid saved-grid">{saved.map(item=><PropertyCard key={item.id} property={item} onUnsave={id=>setSaved(items=>items.filter(p=>p.id!==id))}/>)}</div>:<div className="dashboard-empty">Properties you save will appear here.</div>}</>:<><p className="eyebrow green">SECURITY</p><h1>Change password</h1><form action={password} className="profile-form"><label>Current password<input type="password" name="currentPassword" required/></label><label>New password<input type="password" name="newPassword" minLength={8} required/></label><label>Confirm new password<input type="password" name="confirmPassword" minLength={8} required/></label><button className="primary-button"><KeyRound/> Update password</button></form></>}{feedback&&<div className="form-feedback profile-feedback">{feedback}</div>}</main></div>
}
