import { Route, Routes } from 'react-router-dom'
import { PublicLayout } from './components/layout/PublicLayout'
import { HomePage } from './pages/HomePage'
import { PropertiesPage } from './pages/PropertiesPage'
import { PropertyDetailPage } from './pages/PropertyDetailPage'
import { MarketInsightsPage } from './pages/MarketInsightsPage'
import { BecomeAgentPage } from './pages/BecomeAgentPage'
import { PlaceholderPage } from './pages/PlaceholderPage'
import { ProfilePage } from './pages/ProfilePage'
import { DashboardLayout } from './components/layout/DashboardLayout'
import { RoleRoute } from './components/auth/RoleRoute'
import { AgentOverviewPage } from './pages/dashboard/AgentOverviewPage'
import { AgentPropertiesPage } from './pages/dashboard/AgentPropertiesPage'
import { AgentMessagesPage } from './pages/dashboard/AgentMessagesPage'
import { AdminApplicationsPage, AdminOverviewPage, AdminPropertiesPage, AdminUsersPage } from './pages/dashboard/AdminPages'

export default function App(){return <Routes><Route element={<PublicLayout/>}><Route index element={<HomePage/>}/><Route path="properties" element={<PropertiesPage/>}/><Route path="properties/:slug" element={<PropertyDetailPage/>}/><Route path="market-insights" element={<MarketInsightsPage/>}/><Route path="become-an-agent" element={<BecomeAgentPage/>}/><Route path="profile" element={<ProfilePage/>}/><Route path="*" element={<PlaceholderPage title="Page not found"/>}/></Route><Route path="agent" element={<RoleRoute roles={['agent','admin']}><DashboardLayout/></RoleRoute>}><Route index element={<AgentOverviewPage/>}/><Route path="properties" element={<AgentPropertiesPage/>}/><Route path="messages" element={<AgentMessagesPage/>}/></Route><Route path="admin" element={<RoleRoute roles={['admin']}><DashboardLayout admin/></RoleRoute>}><Route index element={<AdminOverviewPage/>}/><Route path="properties" element={<AdminPropertiesPage/>}/><Route path="users" element={<AdminUsersPage/>}/><Route path="applications" element={<AdminApplicationsPage/>}/></Route></Routes>}
