"""Initial relational schema

Revision ID: 09624c5712f8
Revises: 
Create Date: 2026-08-06 03:35:17.261372

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '09624c5712f8'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('amenities',
    sa.Column('name', sa.String(length=80), nullable=False),
    sa.Column('slug', sa.String(length=90), nullable=False),
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_amenities')),
    sa.UniqueConstraint('name', name=op.f('uq_amenities_name')),
    sa.UniqueConstraint('slug', name=op.f('uq_amenities_slug'))
    )
    with op.batch_alter_table('amenities', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_amenities_created_at'), ['created_at'], unique=False)

    op.create_table('users',
    sa.Column('email', sa.String(length=255), nullable=False),
    sa.Column('password_hash', sa.String(length=255), nullable=False),
    sa.Column('first_name', sa.String(length=80), nullable=False),
    sa.Column('last_name', sa.String(length=80), nullable=False),
    sa.Column('phone', sa.String(length=40), nullable=True),
    sa.Column('avatar_url', sa.String(length=500), nullable=True),
    sa.Column('agency_name', sa.String(length=160), nullable=True),
    sa.Column('role', sa.Enum('USER', 'AGENT', 'ADMIN', name='userrole'), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_users'))
    )
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_users_created_at'), ['created_at'], unique=False)
        batch_op.create_index(batch_op.f('ix_users_email'), ['email'], unique=True)
        batch_op.create_index(batch_op.f('ix_users_role'), ['role'], unique=False)

    op.create_table('agent_applications',
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('full_name', sa.String(length=180), nullable=False),
    sa.Column('email', sa.String(length=255), nullable=False),
    sa.Column('phone', sa.String(length=40), nullable=False),
    sa.Column('city', sa.String(length=100), nullable=False),
    sa.Column('agency_name', sa.String(length=160), nullable=True),
    sa.Column('experience', sa.String(length=180), nullable=True),
    sa.Column('message', sa.Text(), nullable=False),
    sa.Column('status', sa.Enum('PENDING', 'APPROVED', 'REJECTED', name='applicationstatus'), nullable=False),
    sa.Column('reviewed_by_id', sa.Integer(), nullable=True),
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['reviewed_by_id'], ['users.id'], name=op.f('fk_agent_applications_reviewed_by_id_users'), ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], name=op.f('fk_agent_applications_user_id_users'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_agent_applications'))
    )
    with op.batch_alter_table('agent_applications', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_agent_applications_created_at'), ['created_at'], unique=False)
        batch_op.create_index(batch_op.f('ix_agent_applications_status'), ['status'], unique=False)
        batch_op.create_index(batch_op.f('ix_agent_applications_user_id'), ['user_id'], unique=False)

    op.create_table('properties',
    sa.Column('agent_id', sa.Integer(), nullable=False),
    sa.Column('title', sa.String(length=180), nullable=False),
    sa.Column('slug', sa.String(length=220), nullable=False),
    sa.Column('description', sa.Text(), nullable=False),
    sa.Column('price', sa.Numeric(precision=14, scale=2), nullable=False),
    sa.Column('purpose', sa.Enum('SALE', 'RENT', name='listingpurpose'), nullable=False),
    sa.Column('property_type', sa.Enum('APARTMENT', 'HOUSE', 'VILLA', 'COMMERCIAL', 'LAND', name='propertytype'), nullable=False),
    sa.Column('status', sa.Enum('DRAFT', 'ACTIVE', 'ARCHIVED', name='propertystatus'), nullable=False),
    sa.Column('city', sa.String(length=100), nullable=False),
    sa.Column('address', sa.String(length=220), nullable=False),
    sa.Column('bedrooms', sa.Integer(), nullable=True),
    sa.Column('bathrooms', sa.Integer(), nullable=True),
    sa.Column('area_sqm', sa.Numeric(precision=10, scale=2), nullable=False),
    sa.Column('parking_spaces', sa.Integer(), nullable=True),
    sa.Column('floor', sa.Integer(), nullable=True),
    sa.Column('year_built', sa.Integer(), nullable=True),
    sa.Column('views', sa.Integer(), nullable=False),
    sa.Column('is_featured', sa.Boolean(), nullable=False),
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['agent_id'], ['users.id'], name=op.f('fk_properties_agent_id_users'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_properties'))
    )
    with op.batch_alter_table('properties', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_properties_agent_id'), ['agent_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_properties_area_sqm'), ['area_sqm'], unique=False)
        batch_op.create_index(batch_op.f('ix_properties_city'), ['city'], unique=False)
        batch_op.create_index(batch_op.f('ix_properties_created_at'), ['created_at'], unique=False)
        batch_op.create_index(batch_op.f('ix_properties_is_featured'), ['is_featured'], unique=False)
        batch_op.create_index(batch_op.f('ix_properties_price'), ['price'], unique=False)
        batch_op.create_index(batch_op.f('ix_properties_property_type'), ['property_type'], unique=False)
        batch_op.create_index(batch_op.f('ix_properties_purpose'), ['purpose'], unique=False)
        batch_op.create_index(batch_op.f('ix_properties_slug'), ['slug'], unique=True)
        batch_op.create_index(batch_op.f('ix_properties_status'), ['status'], unique=False)
        batch_op.create_index(batch_op.f('ix_properties_title'), ['title'], unique=False)

    op.create_table('favorites',
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('property_id', sa.Integer(), nullable=False),
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['property_id'], ['properties.id'], name=op.f('fk_favorites_property_id_properties'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], name=op.f('fk_favorites_user_id_users'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_favorites')),
    sa.UniqueConstraint('user_id', 'property_id', name=op.f('uq_favorites_user_id'))
    )
    with op.batch_alter_table('favorites', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_favorites_created_at'), ['created_at'], unique=False)
        batch_op.create_index(batch_op.f('ix_favorites_property_id'), ['property_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_favorites_user_id'), ['user_id'], unique=False)

    op.create_table('inquiries',
    sa.Column('sender_id', sa.Integer(), nullable=False),
    sa.Column('agent_id', sa.Integer(), nullable=False),
    sa.Column('property_id', sa.Integer(), nullable=False),
    sa.Column('message', sa.Text(), nullable=False),
    sa.Column('is_read', sa.Boolean(), nullable=False),
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['agent_id'], ['users.id'], name=op.f('fk_inquiries_agent_id_users'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['property_id'], ['properties.id'], name=op.f('fk_inquiries_property_id_properties'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['sender_id'], ['users.id'], name=op.f('fk_inquiries_sender_id_users'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_inquiries'))
    )
    with op.batch_alter_table('inquiries', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_inquiries_agent_id'), ['agent_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_inquiries_created_at'), ['created_at'], unique=False)
        batch_op.create_index(batch_op.f('ix_inquiries_is_read'), ['is_read'], unique=False)
        batch_op.create_index(batch_op.f('ix_inquiries_property_id'), ['property_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_inquiries_sender_id'), ['sender_id'], unique=False)

    op.create_table('property_amenities',
    sa.Column('property_id', sa.Integer(), nullable=False),
    sa.Column('amenity_id', sa.Integer(), nullable=False),
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['amenity_id'], ['amenities.id'], name=op.f('fk_property_amenities_amenity_id_amenities'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['property_id'], ['properties.id'], name=op.f('fk_property_amenities_property_id_properties'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_property_amenities')),
    sa.UniqueConstraint('property_id', 'amenity_id', name=op.f('uq_property_amenities_property_id'))
    )
    with op.batch_alter_table('property_amenities', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_property_amenities_created_at'), ['created_at'], unique=False)

    op.create_table('property_images',
    sa.Column('property_id', sa.Integer(), nullable=False),
    sa.Column('url', sa.String(length=700), nullable=False),
    sa.Column('alt_text', sa.String(length=220), nullable=True),
    sa.Column('position', sa.Integer(), nullable=False),
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['property_id'], ['properties.id'], name=op.f('fk_property_images_property_id_properties'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_property_images'))
    )
    with op.batch_alter_table('property_images', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_property_images_created_at'), ['created_at'], unique=False)
        batch_op.create_index(batch_op.f('ix_property_images_property_id'), ['property_id'], unique=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('property_images', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_property_images_property_id'))
        batch_op.drop_index(batch_op.f('ix_property_images_created_at'))

    op.drop_table('property_images')
    with op.batch_alter_table('property_amenities', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_property_amenities_created_at'))

    op.drop_table('property_amenities')
    with op.batch_alter_table('inquiries', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_inquiries_sender_id'))
        batch_op.drop_index(batch_op.f('ix_inquiries_property_id'))
        batch_op.drop_index(batch_op.f('ix_inquiries_is_read'))
        batch_op.drop_index(batch_op.f('ix_inquiries_created_at'))
        batch_op.drop_index(batch_op.f('ix_inquiries_agent_id'))

    op.drop_table('inquiries')
    with op.batch_alter_table('favorites', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_favorites_user_id'))
        batch_op.drop_index(batch_op.f('ix_favorites_property_id'))
        batch_op.drop_index(batch_op.f('ix_favorites_created_at'))

    op.drop_table('favorites')
    with op.batch_alter_table('properties', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_properties_title'))
        batch_op.drop_index(batch_op.f('ix_properties_status'))
        batch_op.drop_index(batch_op.f('ix_properties_slug'))
        batch_op.drop_index(batch_op.f('ix_properties_purpose'))
        batch_op.drop_index(batch_op.f('ix_properties_property_type'))
        batch_op.drop_index(batch_op.f('ix_properties_price'))
        batch_op.drop_index(batch_op.f('ix_properties_is_featured'))
        batch_op.drop_index(batch_op.f('ix_properties_created_at'))
        batch_op.drop_index(batch_op.f('ix_properties_city'))
        batch_op.drop_index(batch_op.f('ix_properties_area_sqm'))
        batch_op.drop_index(batch_op.f('ix_properties_agent_id'))

    op.drop_table('properties')
    with op.batch_alter_table('agent_applications', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_agent_applications_user_id'))
        batch_op.drop_index(batch_op.f('ix_agent_applications_status'))
        batch_op.drop_index(batch_op.f('ix_agent_applications_created_at'))

    op.drop_table('agent_applications')
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_users_role'))
        batch_op.drop_index(batch_op.f('ix_users_email'))
        batch_op.drop_index(batch_op.f('ix_users_created_at'))

    op.drop_table('users')
    with op.batch_alter_table('amenities', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_amenities_created_at'))

    op.drop_table('amenities')
    # ### end Alembic commands ###
