"""Add property integrity constraints

Revision ID: 193591bf4d83
Revises: 09624c5712f8
Create Date: 2026-08-06 04:07:23.956085

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '193591bf4d83'
down_revision = '09624c5712f8'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('properties', schema=None) as batch_op:
        batch_op.create_check_constraint(batch_op.f('ck_properties_nonnegative_bathrooms'), 'bathrooms IS NULL OR bathrooms >= 0')
        batch_op.create_check_constraint(batch_op.f('ck_properties_nonnegative_bedrooms'), 'bedrooms IS NULL OR bedrooms >= 0')
        batch_op.create_check_constraint(batch_op.f('ck_properties_positive_area'), 'area_sqm > 0')
        batch_op.create_check_constraint(batch_op.f('ck_properties_positive_price'), 'price > 0')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('properties', schema=None) as batch_op:
        batch_op.drop_constraint(batch_op.f('ck_properties_positive_price'), type_='check')
        batch_op.drop_constraint(batch_op.f('ck_properties_positive_area'), type_='check')
        batch_op.drop_constraint(batch_op.f('ck_properties_nonnegative_bedrooms'), type_='check')
        batch_op.drop_constraint(batch_op.f('ck_properties_nonnegative_bathrooms'), type_='check')

    # ### end Alembic commands ###
